### PR TITLE
Warn when building assets from files if some referenced contexts are missing

### LINKED ISSUE #1616: Warn at asset building time when a syntax definition context reference can't be resolved
It would be great to make use of the new syntect API to detect when a syntax definition has some context references (specifically push/set targets - missing includes are not such a problem and can be just treated as warnings) which couldn't be linked/resolved and fail the CI build. https://github.com/sharkdp/bat/issues/915#issuecomment-823581511

### PR DESCRIPTION
**Pull request by keith-hall**
Upgrade to syntect 4.6.0 and add a warning to stdout when building assets from files and some context references are unresolved. Fixes #1616 and makes it easier to work on #915 and prevent such cases occurring again in future :)

### CODE REVIEW

File: src/assets.rs [hunk 1]
```diff
@@ -111,8 +111,17 @@ impl HighlightingAssets {
             );
         }
 
+        let syntax_set = syntax_set_builder.build();
+        let missing_contexts = syntax_set.find_unlinked_contexts();
+        if missing_contexts.len() > 0 {
```
Comment (Enselic) [inline src/assets.rs:116]: Nice! Just fix this lint and this PR is golden:

```
warning: length comparison to zero
   --> src/assets.rs:116:12
    |
116 |         if missing_contexts.len() > 0 {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: using `!is_empty` is clearer and more explicit: `!missing_contexts.is_empty()`
    |
    = note: `#[warn(clippy::len_zero)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
```

I did a test-run of the code and it seemed to work fine for me too :)

**Review by Enselic — APPROVED** [review]

**Review by sharkdp — APPROVED** [review]

**Review by Enselic — APPROVED** [review]

**Comment by Enselic** [comment]
@keith-hall Oh, I just noticed, seems like you forgot to git add the changes to `Cargo.lock` ?

**Review by Enselic — CHANGES_REQUESTED** [review]
Cargo.lock seems forgotten?

**Comment by Enselic** [comment]
Our CI is supposed to detect this, but it appears as if us forgetting to pass `--locked` to early `cargo` commands fixed `Cargo.lock` for later commands.

I just created a [PR](https://github.com/sharkdp/bat/pull/1772) that fixes this. I verified that with this CI fix, this PR would cause [CI to fail](https://github.com/Enselic/bat/pull/19/checks):

**Review by Enselic — APPROVED** [review]
:+1:
