### PR TITLE
Fix syntax highlighting for symlinked files by resolving target path

### LINKED ISSUE #1001: no syntax highlighting for symlinked file
See https://github.com/sharkdp/bat/issues/984#issuecomment-627998442. 

**What version of `bat` are you using?**
bat 0.15.1

**Describe the bug you encountered:**
`bat ~/.ssh/config` is showing the contents of my ssh_config in all white. This might be because ~/.ssh/config is symlinked (`ln -s`) to a file in my dotfiles repo. 

**Describe what you expected to happen?**
`bat ~/.ssh/config` should highlight the contents of the file according to https://github.com/robballou/sublimetext-sshconfig. 

**How did you install `bat`?**
Homebrew

---

system
------

**$ uname -srm**
Darwin 19.5.0 x86_64  

**$ sw_vers**
ProductName:	Mac OS X  
ProductVersion:	10.15.5  
BuildVersion:	19F83c  

bat
---

**$ bat --version**
bat 0.15.1  

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)

### PR DESCRIPTION
**Pull request by Xavrir**
## Summary

When a symlink name has no recognizable extension (e.g. `Aliases/0install` → `../Formula/zero-install.rb`), syntax detection fails because the symlink path doesn't match any syntax. The target file's `.rb` extension would match Ruby, but was never consulted.

This adds a canonicalization fallback in `get_syntax()`: when path-based syntax detection fails with `UndetectedSyntax`, resolve symlinks via `fs::canonicalize()` and retry detection with the target path.

### Priority chain (preserved):
1. Try syntax by given path (existing — covers cases like `.ssh/config` symlink)
2. **If that fails and the canonicalized path differs, try syntax by resolved target path (NEW)**
3. Try first-line syntax detection (existing fallback)
4. Try `--fallback-syntax` (existing fallback)

## Changes

- `src/assets.rs`: Add symlink resolution fallback in `get_syntax()`, properly propagating `UnknownSyntax` errors from resolved-path detection while only retrying on `UndetectedSyntax`
- New test `syntax_detection_for_symlinked_file_by_target_extension` — mirrors the homebrew-core `Aliases/0install` scenario from the issue
- CHANGELOG entry

## Testing

- 378 tests pass (`cargo test`)
- Existing `syntax_detection_for_symlinked_file` test still passes (`.ssh/config` symlink matched by symlink path, canonicalize fallback never reached)
- New test: `Aliases/0install` (no extension) → `Formula/zero-install.rb` → correctly detects Ruby syntax

## Related

- Closes #1001
- Based on @keith-hall's [experimental fix suggestion](https://github.com/sharkdp/bat/issues/1001#issuecomment-1227847073) using `canonicalize()`
- PR #1019 partially fixed the original report but didn't handle the case where the symlink name has no extension

### CODE REVIEW

File: src/assets.rs [hunk 1]
```diff
@@ -223,18 +223,38 @@ impl HighlightingAssets {
...
+                }
+                Err(e)
+            })
         } else {
             Err(Error::UndetectedSyntax("[unknown]".into()))
         };
 
         match path_syntax {
-            // If a path wasn't provided, or if path based syntax detection
-            // above failed, we fall back to first-line syntax detection.
```
Comment (keith-hall) [inline src/assets.rs:237]: maybe this comment is still relevant?

Comment (Xavrir) [reply src/assets.rs:237]: Good catch, restored it.
