### PR TITLE
Fix #1413 Can't use `bat` at all! (Error: Use of bat as a pager is di…

### LINKED ISSUE #1413: Can't use `bat` at all! (Error: Use of bat as a pager is disallowed...)
**What version of `bat` are you using?**
bat 0.17.1

**Describe the bug you encountered:**

Whenever I use `bat`, I'm shown the following error message:

> [bat error]: Use of bat as a pager is disallowed in order to avoid infinite recursion problems

I believe this started happening after a certain update but can't exactly pinpoint which one. I've uninstalled and reinstalled `bat` again but with no luck.

**What did you expect to happen instead?**
For `bat` to display the contents as usual.

**How did you install `bat`?**
Homebrew

---

system
------

**$ uname -srm**
Darwin 20.1.0 x86_64  

**$ sw_vers**
ProductName:	macOS  
ProductVersion:	11.0.1  
BuildVersion:	20B29  

bat
---

**$ bat --version**
bat 0.17.1  

**$ env**
PAGER=bat  

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)

### PR DESCRIPTION
**Pull request by Enselic**
…sallowed...)

Fixed by implementing the proposal by sharkdp:

* Allow PAGER=bat, but ignore the setting in bat and simply default to
  less. Unless of course, BAT_PAGER or --pager is used to overwrite the
  value of PAGER.

* Disallow the usage of bat within BAT_PAGER and --pager.

### CODE REVIEW

File: src/pager.rs [hunk 1]
```diff
@@ -98,10 +98,20 @@ pub(crate) fn get_pager(config_pager: Option<&str>) -> Result<Option<Pager>, Par
...
+                    let no_color_support = kind == PagerKind::More || kind == PagerKind::Most;
+
+                    // If PAGER=bat, silently use 'less' instead to prevent recursion ...
+                    let is_self = kind == PagerKind::Bat;
+
+                    no_color_support || is_self
+                },
+                // Never silently replace with less if bat-specific means to set a pager is used
+                _ => false
+            } ;
```
Comment (sharkdp) [inline src/pager.rs:114]: Maybe this would be a bit clearer? (with added comments)
``` rust
let use_less_instead = match (source, kind) {
  (PagerSource::EnvVarPager, PagerKind::More) => true,
  (PagerSource::EnvVarPager, PagerKind::Most) => true,
  (PagerSource::EnvVarPager, PagerKind::Bat) => true,
  _ => false,
};
```

File: src/pager.rs [hunk 2]
```diff
@@ -98,10 +98,20 @@ pub(crate) fn get_pager(config_pager: Option<&str>) -> Result<Option<Pager>, Par
...
+                    // 'more' and 'most' do not supports colors; automatically use 'less' instead
+                    // if the problematic pager came from the generic PAGER env var
+                    let no_color_support = kind == PagerKind::More || kind == PagerKind::Most;
+
+                    // If PAGER=bat, silently use 'less' instead to prevent recursion ...
+                    let is_self = kind == PagerKind::Bat;
+
+                    no_color_support || is_self
+                },
+                // Never silently replace with less if bat-specific means to set a pager is used
```
Comment (sharkdp) [inline src/pager.rs:112]: Took my a while to understand this comment. Maybe:
"Never silently use less if BAT_PAGER or --pager has been specified"

**Comment by sharkdp** [comment]
Great how this can now be easily solved with the previous changes!

File: src/pager.rs (hunk 1 above)
Comment (Enselic) [reply src/pager.rs:114]: Agreed, I will change to something like that. I especially like that the deepest level of indentation is reduced by one.

**Review by sharkdp — APPROVED** [review]
